site_name: Omeka-S Documentation 
site_description: Documentation for 91.9 KCSB FM 2024-2025


nav:
  - Home: index.md
  - Introduction: introduction.md
  - System Requirements: system-requirements.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide:
      - Accessing the Website: user-guide.md#accessing-the-website
      - User Roles and Permissions: user-guide.md#user-roles-and-permissions
      - Creating and Managing Content: user-guide.md#creating-and-managing-content
      - Plugins and Themes: user-guide.md#plugins-and-themes
  - Maintenance and Troubleshooting: maintenance.md
  - FAQ: faq.md
  - Appendices:
      - Glossary: appendices.md#glossary
      - Additional Resources: appendices.md#additional-resources

theme:
  name: material

