
site_name: Omeka-S Documentation 
site_description: Documentation for 91.9 KCSB FM 2024-2025

nav:
  - Home: index.md
  - Introduction: introduction.md
  - System Requirements: system-requirements.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide: user-guide.md
  - Maintenance: maintenance.md
  - FAQ: faq.md
  - Appendix: appendices.md
theme:
  name: flatly
  custom_dir: docs/overrides

extra_css: 
- css/custom.css
